//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sales.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sales.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاجراءات.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ ااضافه.
        /// </summary>
        public static string AddedOn {
            get {
                return ResourceManager.GetString("AddedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة فئة.
        /// </summary>
        public static string AddNewCategory {
            get {
                return ResourceManager.GetString("AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة عميل جديد .
        /// </summary>
        public static string AddNewCustomer {
            get {
                return ResourceManager.GetString("AddNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء فاتورة مبيعات.
        /// </summary>
        public static string AddNewInvoice {
            get {
                return ResourceManager.GetString("AddNewInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  اضافة صنف.
        /// </summary>
        public static string addProduct {
            get {
                return ResourceManager.GetString("addProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل ترغب في الاستمرار في مسح الصنف ؟.
        /// </summary>
        public static string AreyousurethatyouDeleltthisProduct {
            get {
                return ResourceManager.GetString("AreyousurethatyouDeleltthisProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل ترغب في الاستمرار في المسح ؟.
        /// </summary>
        public static string Areyousureyouwanttodeletethis {
            get {
                return ResourceManager.GetString("Areyousureyouwanttodeletethis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجوع الي الفواتير.
        /// </summary>
        public static string BacktoInvoices {
            get {
                return ResourceManager.GetString("BacktoInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئات.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفئه.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفئة.
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفئة يجب ألا يزيد عن 20 حرف.
        /// </summary>
        public static string Categorynamecannotexceed20characters {
            get {
                return ResourceManager.GetString("Categorynamecannotexceed20characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  اسم الفئة مطلوب.
        /// </summary>
        public static string Categorynameisrequired {
            get {
                return ResourceManager.GetString("Categorynameisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار العميل.
        /// </summary>
        public static string ChooseaClient {
            get {
                return ResourceManager.GetString("ChooseaClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار صنف.
        /// </summary>
        public static string Chooseproduct {
            get {
                return ResourceManager.GetString("Chooseproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان العميل مطلوب.
        /// </summary>
        public static string ClientAddressRequired {
            get {
                return ResourceManager.GetString("ClientAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ العميل بنجاح.
        /// </summary>
        public static string ClientCreated {
            get {
                return ResourceManager.GetString("ClientCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف العميل بنجاح.
        /// </summary>
        public static string ClientDeleted {
            get {
                return ResourceManager.GetString("ClientDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال اسم العميل كاملا.
        /// </summary>
        public static string ClientNameRequired {
            get {
                return ResourceManager.GetString("ClientNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال رقم تلفون العميل.
        /// </summary>
        public static string ClientPhoneRequired {
            get {
                return ResourceManager.GetString("ClientPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل بيانات العميل بنجاح.
        /// </summary>
        public static string ClientUpdated {
            get {
                return ResourceManager.GetString("ClientUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل ترغب في الاستمرار في استخدام الموقع؟.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل مستخدم جديد.
        /// </summary>
        public static string CreateAnewUser {
            get {
                return ResourceManager.GetString("CreateAnewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء مستخدم جديد.
        /// </summary>
        public static string CreatenewUser {
            get {
                return ResourceManager.GetString("CreatenewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال اسم الفئة.
        /// </summary>
        public static string CtaegoryName {
            get {
                return ResourceManager.GetString("CtaegoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العميل.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العميل.
        /// </summary>
        public static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العميل مطلوب.
        /// </summary>
        public static string CustomerIDisrequired {
            get {
                return ResourceManager.GetString("CustomerIDisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان يكون طول الاحرف اقل من 100.
        /// </summary>
        public static string Customernamecannotexceed100characters {
            get {
                return ResourceManager.GetString("Customernamecannotexceed100characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل مطلوب.
        /// </summary>
        public static string Customernameisrequired {
            get {
                return ResourceManager.GetString("Customernameisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف يجب ألا يزيد عن 200 حرف.
        /// </summary>
        public static string Descriptioncannotexceed200characters {
            get {
                return ResourceManager.GetString("Descriptioncannotexceed200characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل رقم موجي.
        /// </summary>
        public static string Discountmustbeapositivevalue {
            get {
                return ResourceManager.GetString("Discountmustbeapositivevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (%) خصم علي الصنف.
        /// </summary>
        public static string Discountproduct {
            get {
                return ResourceManager.GetString("Discountproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصم.
        /// </summary>
        public static string Dscount {
            get {
                return ResourceManager.GetString("Dscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل.
        /// </summary>
        public static string Editaed {
            get {
                return ResourceManager.GetString("Editaed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الفئة.
        /// </summary>
        public static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل العميل.
        /// </summary>
        public static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل الصنف.
        /// </summary>
        public static string EditPrudect {
            get {
                return ResourceManager.GetString("EditPrudect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاميل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني مطلوب.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل خصم الفاتورة.
        /// </summary>
        public static string EnterInvoiceDiscount {
            get {
                return ResourceManager.GetString("EnterInvoiceDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل خصم صنف.
        /// </summary>
        public static string EnterproductDiscount {
            get {
                return ResourceManager.GetString("EnterproductDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاول.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول يجب أن لا يتجاوز 50 حرف.
        /// </summary>
        public static string FirstNameLength {
            get {
                return ResourceManager.GetString("FirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول مطلوب.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انثي.
        /// </summary>
        public static string fmail {
            get {
                return ResourceManager.GetString("fmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم كاملا.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى اختيار قيمة صحيحة للجنس.
        /// </summary>
        public static string GenderRange {
            get {
                return ResourceManager.GetString("GenderRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحقل مطلوب.
        /// </summary>
        public static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم او كلمة المرور غير صحيحة.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال بريد إلكتروني صالح.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال رقم هاتف صالح.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ الفاتورة بنجاح.
        /// </summary>
        public static string InvoiceCreated {
            get {
                return ResourceManager.GetString("InvoiceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الفاتورة.
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الفاتورة.
        /// </summary>
        public static string InvoiceDetails {
            get {
                return ResourceManager.GetString("InvoiceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (%) خصم علي الفاتورة .
        /// </summary>
        public static string InvoiceDiscount {
            get {
                return ResourceManager.GetString("InvoiceDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصم الفاتورة يجب  ان يكون رقم موجب.
        /// </summary>
        public static string Invoicediscountmustbeapositivevalue {
            get {
                return ResourceManager.GetString("Invoicediscountmustbeapositivevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتورة.
        /// </summary>
        public static string InvoiceId {
            get {
                return ResourceManager.GetString("InvoiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاتورة مطلوب.
        /// </summary>
        public static string InvoiceIdRequired {
            get {
                return ResourceManager.GetString("InvoiceIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفواتير.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الفاتورة بعد الخصم.
        /// </summary>
        public static string InvoiceValueAfterDiscount {
            get {
                return ResourceManager.GetString("InvoiceValueAfterDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ الصنف بنجاح.
        /// </summary>
        public static string ItemCreated {
            get {
                return ResourceManager.GetString("ItemCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاخير.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاخير يجب أن لا يتجاوز 50 حرف.
        /// </summary>
        public static string LastNameLength {
            get {
                return ResourceManager.GetString("LastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاخير مطلوب.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفئة.
        /// </summary>
        public static string NameCategory {
            get {
                return ResourceManager.GetString("NameCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل.
        /// </summary>
        public static string NameCustomer {
            get {
                return ResourceManager.GetString("NameCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم اضافة فئات! .
        /// </summary>
        public static string NoCategoryAddedYet {
            get {
                return ResourceManager.GetString("NoCategoryAddedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! لم يتم اضافة عملاء.
        /// </summary>
        public static string NoCustomerAddedYet {
            get {
                return ResourceManager.GetString("NoCustomerAddedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم اضافة اصناف.
        /// </summary>
        public static string NoProductAddedYet {
            get {
                return ResourceManager.GetString("NoProductAddedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم السري.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور لا يجب أن تتجاوز 256 حرف.
        /// </summary>
        public static string Passwordcannotexceed256characters {
            get {
                return ResourceManager.GetString("Passwordcannotexceed256characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور مطلوبة.
        /// </summary>
        public static string Passwordrequired {
            get {
                return ResourceManager.GetString("Passwordrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التلفون.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف مطلوب.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر بعد الخصم.
        /// </summary>
        public static string PriceAfterDiscount {
            get {
                return ResourceManager.GetString("PriceAfterDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون سعر المنتج أكبر من 0.
        /// </summary>
        public static string PriceProductMustGreaterthan0 {
            get {
                return ResourceManager.GetString("PriceProductMustGreaterthan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر المنتج مطلوب.
        /// </summary>
        public static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل الصنف.
        /// </summary>
        public static string ProductDetail {
            get {
                return ResourceManager.GetString("ProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الصنف.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الصنف مطلوب.
        /// </summary>
        public static string ProductIDisrequired {
            get {
                return ResourceManager.GetString("ProductIDisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الصنف.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنتج يجب ألا يتجاوز 100 حرف.
        /// </summary>
        public static string Productnamecannotexceed100characters {
            get {
                return ResourceManager.GetString("Productnamecannotexceed100characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنتج مطلوب.
        /// </summary>
        public static string Productnameisrequired {
            get {
                return ResourceManager.GetString("Productnameisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاصناف.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب كمية.
        /// </summary>
        public static string Quantityisrequired {
            get {
                return ResourceManager.GetString("Quantityisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقل كمية يجب ان تكون 1.
        /// </summary>
        public static string Quantitymustbeatleast1 {
            get {
                return ResourceManager.GetString("Quantitymustbeatleast1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبايعات.
        /// </summary>
        public static string Salse {
            get {
                return ResourceManager.GetString("Salse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Sava {
            get {
                return ResourceManager.GetString("Sava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العميل.
        /// </summary>
        public static string SelectedCustomerId {
            get {
                return ResourceManager.GetString("SelectedCustomerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العميل مطلوب.
        /// </summary>
        public static string SelectedCustomerIDisrequired {
            get {
                return ResourceManager.GetString("SelectedCustomerIDisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختير الجنس.
        /// </summary>
        public static string SelectGender {
            get {
                return ResourceManager.GetString("SelectGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال اسم العميل كاملا.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم بنجاح.
        /// </summary>
        public static string Successed {
            get {
                return ResourceManager.GetString("Successed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ الاجمالي.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة الفاتورة الكليه.
        /// </summary>
        public static string TotalInvoiceValue {
            get {
                return ResourceManager.GetString("TotalInvoiceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وحدة السعر.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب وحدة السعر.
        /// </summary>
        public static string Unitpriceisrequired {
            get {
                return ResourceManager.GetString("Unitpriceisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون وحدة السعر أكبر من 0.
        /// </summary>
        public static string Unitpricemustbegreaterthan0 {
            get {
                return ResourceManager.GetString("Unitpricemustbegreaterthan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم .
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم لا يجب أن يتجاوز 100 حرف.
        /// </summary>
        public static string Usernamecannotexceed100characters {
            get {
                return ResourceManager.GetString("Usernamecannotexceed100characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم مطلوب.
        /// </summary>
        public static string Usernamerequired {
            get {
                return ResourceManager.GetString("Usernamerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا !.
        /// </summary>
        public static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء استرجاع السعر.
        /// </summary>
        public static string WrongReturnPrice {
            get {
                return ResourceManager.GetString("WrongReturnPrice", resourceCulture);
            }
        }
    }
}
